

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bencidata_django
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - .env
    environment:             
      DJANGO_SUPERUSER_EMAIL: leopoldowall9@gmail.com
      DJANGO_SUPERUSER_PASSWORD: admin123
      DJANGO_SUPERUSER_USERNAME: admin
    depends_on:
      - db
    networks:
      - bencidata_network

  db:
    image: postgres:15
    container_name: bencidata_postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bencidata_network

  metabase:
    image: metabase/metabase:latest
    container_name: bencidata_metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: ${DB_USER}
      MB_DB_PASS: ${DB_PASSWORD}
      MB_DB_HOST: db
      MB_ENCRYPTION_SECRET_KEY: "zncD@t4_2025_M3tabase_K3y_Sh0uldBeVeryLong"
    depends_on:
      - db
    networks:
      - bencidata_network


  nginx:
    image: nginx:latest
    container_name: bencidata_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - django
    networks:
      - bencidata_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  bencidata_network:
    driver: bridge
