services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    image: bencidata-django
    container_name: bencidata_django
    command: /entrypoint.sh
    volumes:
      - .:/app
      - static_volume:/app/staticfiles     # STATIC_ROOT
      - media_volume:/app/media
    env_file:
      - .env
    environment:
      DJANGO_SUPERUSER_EMAIL: leopoldowall9@gmail.com
      DJANGO_SUPERUSER_PASSWORD: 123qaz***
      DJANGO_SUPERUSER_USERNAME: Due√±o
    networks:
      - bencidata_network
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    container_name: bencidata_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - django
    networks:
      - bencidata_network

volumes:
  static_volume:
  media_volume:

networks:
  bencidata_network:
    driver: bridge

